#!/bin/bash

GDUP_VERSION='0.0.1-alpha'

VERSIONS=$(curl -Ls https://downloads.tuxfamily.org/godotengine/ \
	| grep -E '^.*<a.*?>([0-9](\.[0-9])+)<\/a>.*$' \
	| sed -E 's/^.*<a.*?>([0-9](\.[0-9])+)<\/a>.*$/\1/g')

function has-version() {
	for v in $VERSIONS; do
		if [[ "$v" == "$1" ]]; then
			return 0
		fi
	done
	return 1
}

if [[ -z $1 ]]; then
	echo "Expected and argument"
	exit 1
fi

if ! [[ -z $2 ]]; then
	echo "Expected only one argument"
	exit 1
fi

if [[ "$1" == "--version" || "$1" == "-v" ]]; then
	echo "GodotUP $GDUP_VERSION"
	exit 1
fi

if ! has-version "$1"; then
	echo "Version '$1' does not exist."
	exit 2
fi

pushd >/dev/null `mktemp -d`

ARCH='unknown'

case "$(uname -om)" in
	"x86_64 GNU/Linux")
		if [[ "$1" =~ ^4(\.[0-9])+$ ]]; then
			ARCH='x86_64'
		else
			ARCH='x11.64'
		fi
		;;
	"i686 GNU/Linux")
		if [[ "$1" =~ ^4(\.[0-9])+$ ]]; then
			ARCH='x86_32'
		else
			ARCH='x11.32'
		fi
		;;
	*)
		echo "Error: Unsupported operating system."
		exit 3
		;;
esac

ZIP=$(curl -Ls "https://downloads.tuxfamily.org/godotengine/${1}/" \
	| grep 'application/zip' \
	| grep -F "$ARCH" \
	| sed -E 's/^.*?<a.*?>(.+?)<\/a>.*$/\1/')
EXE="${ZIP%%.zip}"

URL="https://downloads.tuxfamily.org/godotengine/${1}/${ZIP}"

wget "$URL"
unzip "$ZIP"
rm "$ZIP"

#install "$EXE" -m 775 ~/.local/bin/godot-${1/./'-'}
# Do not replace dots with dashes
install "$EXE" -m 775 ~/.local/bin/godot-$1

popd >/dev/null
